name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker images
      run: docker-compose -f docker-compose.yml build

    - name: Docker login to registry
      run: docker login -u ${{ secrets.docker_hub_user }} -p ${{ secrets.docker_hub_pass }} 

    - name: Build and push Docker images
      run: docker-compose -f docker-compose.yml push
      
